---
name: DBIx-Jello
version: 1e-05
author: ~
abstract: stupidly flexible object storage
license: perl
requires:
  DBD::SQLite: 0
  DBI: 0
  Data::UUID: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
provides:
  DBIx::Jello:
    file: lib/DBIx/Jello.pm
    version: 1e-05
  DBIx::Jello::Class:
    file: lib/DBIx/Jello/Class.pm
generated_by: Module::Build version 0.2612
